[package]
name = "chronicle"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.48", features = ["full"] }
